version: '2'
services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    build:
      context: .
      dockerfile: ./redis/Dockerfile
