"""empty message

Revision ID: 4e5b612a68ca
Revises: ed657e16ce20
Create Date: 2017-05-08 13:34:57.588698

"""

# revision identifiers, used by Alembic.
revision = '4e5b612a68ca'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
